SERVICE_URL="http://localhost:5000/neo4j"
OS_AUTH_URL="http://0.0.0.0:5000/v2.0"
OS_USERNAME=""
OS_PASSWORD=""
OS_PROJECT_ID=""
VERSION="2.0"
PRIVATE_KEY="""-----BEGIN RSA PRIVATE KEY-----
-----END RSA PRIVATE KEY-----"""